# Default values for egressippcapcollection.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "quay.io/support-tools/monitor-tools:latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name: "node-metrics-sa"

tolerations: 
- operator: Exists

namespace:
  name: "egress-ip-pcap"

egressippcapdaemonsetworker:
  name: egressippcapdaemonset-worker
  nodeSelector:
    iperf-client: ""


egressippcapdaemonsetmaster:
  name: egressippcapdaemonset-master
  nodeSelector:
    iperf-server: "" 