#!/bin/bash

DEFAULT_OUTPUT_DIR="/tmp-pcaps"
DEFAULT_HELM_CHART=egress-collect
DEFAULT_NAMESPACE="egress-ip-pcap"
COPY_DIR="/must-gather/"

# Set default args
set_default_args() {
    if [[ "${OUTPUT_DIR}" == "" ]]; then
        echo "Using default output directory: ${DEFAULT_OUTPUT_DIR}"
        OUTPUT_DIR=$DEFAULT_OUTPUT_DIR
    fi

    if [[ "${NAMESPACE}" == "" ]]; then
        echo "Using default namespace: ${DEFAULT_NAMESPACE}"
        NAMESPACE=$DEFAULT_NAMESPACE
    fi
}

collect_pcaps() {
  local pcap_pods
  pcap_pods="$(oc get pods -n ${NAMESPACE} -o jsonpath='{.items[*].metadata.name}' )"

  for pod in $pcap_pods; do
    local node_name="$(oc get pods ${pod} -n ${NAMESPACE} -o jsonpath='{.spec.nodeName}' )"
    local output_dir="${OUTPUT_DIR}/${node_name}"
    
    echo "Collecting pcaps for ${node_name}"
    mkdir -p "$output_dir"
    oc cp -n $NAMESPACE "${pod}:/pcaps/" "${output_dir}"
  done
}

move_collection() {
    echo "Preparing mertics for download"
    mkdir -p $COPY_DIR
    mv $OUTPUT_DIR/* $COPY_DIR/
}

set_default_args
collect_pcaps
move_collection
